version: 0.0
os: linux

files:
  - source: /static/*
    destination: /usr/share/nginx/html/
  - source: /index.html
    destination: /usr/share/nginx/html/

hooks:
  BeforeInstall:
    - location: script/stop_nginx.sh
      timeout: 300
      runas: root
    - location: script/remove_existing_files.sh  # New script to remove existing files
      timeout: 60
      runas: root

  AfterInstall:
    - location: script/deploy.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: script/start_nginx.sh
      timeout: 300
      runas: root
