version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/demo-app
permissions:
  - object: /home/ec2-user/demo-app
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: script/install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: script/start.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: script/stop.sh
      timeout: 300
      runas: ec2-user
