version: 0.0
os: linux

files:
  - source: /static/*
    destination: /usr/share/nginx/html/  # Copy files in static/ to the Nginx html folder
  - source: /index.html
    destination: /usr/share/nginx/html/  # Ensure index.html goes to the correct location

hooks:
  BeforeInstall:
    - location: script/stop_nginx.sh  # Adjusted for script/ directory
      timeout: 300
      runas: root

  AfterInstall:
    - location: script/deploy.sh  # Adjusted for script/ directory
      timeout: 300
      runas: root

  ApplicationStart:
    - location: script/start_nginx.sh  # Adjusted for script/ directory
      timeout: 300
      runas: root
