version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22 # Set this to the Node.js version you need
    commands:
      # Install npm dependencies
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the application...
      - npm run build

  post_build:
    commands:
      - echo Build completed successfully!

artifacts:
  files:
    - '**/*'  # This ensures that all files are included in the artifact
  base-directory: nodejsbuild/build # Ensure this is the directory where your build files are generated
  discard-paths: yes  # Optional: Use this if you want to discard directory structure in the artifact

  