version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22 # Set this to the Node.js version you need
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the application...
      - npm run build
      - pwd
      - echo Copying appspec.yml to build directory...
      - cp appspec.yml build/  # Ensure appspec.yml is included in the build directory
      - echo Copying scripts/ to build directory...
      - cp -r scripts/ build/  # Ensure scripts are included in the build directory

  post_build:
    commands:
      - echo Zipping the build folder...
      - cd build
      - zip -r ../build.zip .  # Zipping the build directory

artifacts:
  files:
    - 'build.zip'  # Zipped build artifact
